### ISSUE TITLE
Ajouter le logo de l'asso

### ISSUE THREAD

**Issue by AxelTerizaki** [Ouestampes/quelleroulotte#2]
Le logo de l'asso devrait se retrouver : 

- Sur la partie publique
- En tant que logo de l'app / fenêtre

Pour le dernier point il faudrait probablement créer un dossier `assets` à la racine et déplacer `public` et `controller` dans un dossier `frontend` à créer, histoire d'être raccord. L'icône irait dans `assets`. Elle peut être alors utilisée lors de la création des fenêtres dans `electron.ts` (voir [l'API d'Electron pour la création de fenêtres `BrowserWindow`](https://www.electronjs.org/docs/latest/api/browser-window)) et pour l'icone de l'app elle-même, [il y a tout un guide sur le site d'Electron Builder](https://www.electron.build/icons)

**Comment by Xefir** [comment]
Comme écrit dans le nom du commit, l’icône n'a pas l'air de charger sous Linux et j'ai pas de Windows sous la main pour tester.
Je veux bien que tu regarde quand tu as le temps @AxelTerizaki , je sèche un peu
