### ISSUE TITLE
[Idée] Mettre en place un menu pour controle accessibilité

### ISSUE THREAD

**Issue by Helmara** [Ouestampes/quelleroulotte#26]
L'idée serait de mettre un menu sur le controller pour permettre de gérer l'accessibiliter sur la fenêtre public.

Idée :
- [ ] Changement de taille des caractères
- [ ] Changement des couleurs
- [ ] Gestion du son ou autre...

**Comment by ebagot** [comment]
Changement de taille de caractères -> #59 
Changement de couleur -> Pour l'instant, pas d'idée d'application
Gestion de son -> #13
