### ISSUE TITLE
Choses manquantes côté affichage public

### ISSUE THREAD

**Issue by AxelTerizaki** [Ouestampes/quelleroulotte#3]
- [x] Catégorie de la question
- [x] Thême
- [x] Le nombre de question déjà posées

Il faut aussi : 

- [x] un **message d'attente** tant que le jeu n'a pas démarré 
- [x] Le titre du jeu

**Comment by AxelTerizaki** [comment]
Ca devrait être sur la miletone V1 non plutôt? Ca me paraît important.

Actuellement l'affichage public est très dégueu :)

**Comment by Xefir** [comment]
C'est quoi le "Thème" ?

**Comment by AxelTerizaki** [comment]
Ouais mais j'imagine que comme là c'est juste l'affichage c'est pas grave. Il faut filtrer par catégorie mais afficher le thème en gros.

**Comment by AxelTerizaki** [comment]
T'as besoin d'aide pour l'affichage du nombre de questions posées ?

**Comment by Xefir** [comment]
Je veux bien, j'ai fixé aujourd'hui les retours de la semaine dernière, mais je sais pas si j'aurais le temps pour ce dernier point avant Samedi. Si tu veux pas attendre, go ! :)
