### ISSUE TITLE
FInalisation de la V1

### ISSUE THREAD

**Issue by Xefir** [Ouestampes/quelleroulotte#36]
- [x] Afficher le numéro de la question sur les deux affichages
- [x] Afficher le temps passé en temps humain (et pas en secondes comme actuellement)
- [x] Passage en plein écran au double clic sur le partie public (et/ou touche F11)
- [x] Augmenter la police globale de la partie public

**Comment by AxelTerizaki** [comment]
Ajout du temps en mode humain via 2cc4943
