### ISSUE TITLE
Choses manquantes sur l'écran de contrôle

### ISSUE THREAD

**Issue by AxelTerizaki** [Ouestampes/quelleroulotte#4]
Pour le moment tout est géré via des menus mais on peut imaginer que la personne voudra plutôt des énormes boutons.

- [x] Déjà reproduire tous les éléments du menu. 
- [x] Un bouton pour retélécharger la liste de questions
- [x] Afficher le nombre de questions chargées 

Pour communiquer avec le backend Electron possède un système d'IPC : 
- L'IPC "main" est celui du backend, de l'executable quoi
- L'IPC "renderer" est celui qu'on trouve dans le chromium embarqué.

Les deux communiquent ensemble et peuvent s'envoyer des évènements et messages.

[L'exemple sur la doc Electron](https://www.electronjs.org/docs/latest/tutorial/ipc) est un peu verbeux mais normalement ce que j'ai déjà fait devrait pas mal aiguiller sur comment s'y prendre (même si ça ne fait que l'envoi de l'IPC main vers le renderer)

**Comment by Xefir** [comment]
> Un bouton pour retélécharger la liste de questions

On est d'accord que cette action ne peux être faite que si la partie n'est pas lancé ?

**Comment by AxelTerizaki** [comment]
> > Un bouton pour retélécharger la liste de questions
> 
> On est d'accord que cette action ne peux être faite que si la partie n'est pas lancé ?

On est des fous furieux ou pas ?

En vrai ça change aps grand chose : la liste est retéléchargée, le JSON doit être relu et remplacer l'ancien. Ensuite comme le jeu pioche des questions dans celles pas encore traitées ça change pas grand chose
