### ISSUE TITLE
La Roulotte Multi-Jeux

### ISSUE THREAD

**Issue by AxelTerizaki** [Ouestampes/quelleroulotte#62]
L'idée que l'app s'appelle toujours "La Roulotte" me plait bien et qu'elle puisse proposer plusieurs jeux, comme une roulotte allant de village en village pour proposer ses curiosités aux habitants, je trouve ça rigolol dans l'idée.

Nock avait l'air de vouloir qu'on puisse automatiser un autre jeu qu'il a fait, NoFilter. 

On discutera du jeu en lui-même plus tard, mais l'objet de cette issue est surtout de réfléchir à un moyen de "modulariser" la roulotte actuelle, pour réutiliser un max de code possible. 

Par exemple : 
- Toute la mécanique de passer à la question suivante, précédente, etc. 
- Importer le contenu du jeu depuis les services google (où on stocke tout) : Gsheet, Drive, etc.
- Gestion des fenêtres
- etc.

Ca va demander un peu de boulot et j'aimerais qu'on clore #43 avant de bosser sur ça. Il ne faut pas tomber dans le piège non plus de *l'overengineering* (qui consiste à beaucoup trop réfléchir et pondre une usine à gaz compliquée) mais je pense qu'il ya  un truc plutôt cool à faire. Le but premier c'est de ne pas avoir à regénérer un deuxième dépôt avec d'autres trucs, ça fait beaucoup de travail à maintenir et on est pas là pour bosser sur des *chores* chiantes mais bien pour s'amuser ! :)

**Comment by ebagot** [comment]
Cf issues #13 #97 #98
