### ISSUE TITLE
Passer à la question en précisant le numéro dans le gsheet

### ISSUE THREAD

**Issue by AxelTerizaki** [Ouestampes/quelleroulotte#7]
Je vois que c'est quelque chose de demandé. Je m'interroge un peu sur le besoin, qui connaît par coeur le numéro de la question ?

Est-ce qu'une rapide interface dans l'outil de contrôle ne serait pas mieux ? Afficher le tableau des questions avec leur ID en gros comme ça le contrôleur peut visualier quelle question il va choisir ?

**Comment by ebagot** [comment]
Effectivement l'issue est imprécise, je vais la reformuler.
